const createError = require("http-errors");
const authRoutes = require("./auth");
const homeRoutes = require("./home");
const adminRoutes = require("./admin");
const purchaseRoutes = require("./purchase");
const privacyRoutes = require("./privacy");
const imprintRoutes = require("./imprint");
const subscriptionRoutes = require("./subscription");
const webhookRoutes = require("./webhook");
const logoutRoutes = require("./logout");
const healthcheckRoutes = require("./healthcheck");
const robotsRoutes = require("./robots");
const errorRoutes = require("./error");
const attachRoute = require("../middlewares/attachRoute");
const csurf = require("@dr.pogodin/csurf");
const csrfProtection = require("../middlewares/csrfProtection")(csurf);

module.exports = function (app, passport, stripe, isAuthenticated) {
  app.use(attachRoute);
  app.use("/", webhookRoutes(stripe));
  app.use("/", csrfProtection, authRoutes(passport));
  app.use("/home", csrfProtection, homeRoutes(stripe, isAuthenticated));
  app.use("/admin", csrfProtection, adminRoutes(isAuthenticated));
  app.use("/", csrfProtection, purchaseRoutes(stripe, isAuthenticated));
  app.use("/", csrfProtection, subscriptionRoutes(stripe, isAuthenticated));
  app.use("/privacy", csrfProtection, privacyRoutes());
  app.use("/imprint", csrfProtection, imprintRoutes());
  app.use("/logout", csrfProtection, logoutRoutes());
  app.use("/healthcheck", csrfProtection, healthcheckRoutes());
  app.use("/", csrfProtection, robotsRoutes());
  app.use("/", csrfProtection, errorRoutes(createError));
};
