name: Deploy to Azure

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'esn-member'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_b9b6dcf4dd1647d5a62f5b12a1c43b2e }}
          images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ed36785579e34fa993482a8be5b87efc }}/esn-hd-member:${{ env.VERSION }}'
