name: Docker

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 3 * * *' # Runs every day at 3AM
  workflow_dispatch: # Allows to manually run this workflow

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2

      -
        name: Get the version
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      -
        name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      -
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date --utc +'%Y-%m-%dT%H:%M:%SZ')"

      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: fabsau/esn-hd-member:${{ env.VERSION }}, fabsau/esn-hd-member:latest
          labels: version=${{ env.VERSION }}
          build-args: |
            BUILD_VERSION=${{ env.VERSION }}
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ steps.date.outputs.date }}
